### ISSUE TITLE
27-28-w01-d04-hw

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/shared_modules#18]
add suggestions here

**Comment by nathanallen** [comment]
I propose that this could be a hmwk-repo with ~4 review questions from the week. This should be submitted with a formal pull request, and would be closely reviewed for code formatting/style.
- An intermediate/advanced kyrel problem.
- An html/css/js boilerplate with prompts to:
  - show off their html/css skills ("impress us!")
    - add element to the page, style it
  - show off their dom manipulation skillz  ("show us what you can do!")
    - modify an element on the page
    - bonus: add a click listener

Due Friday, EOD.

**Comment by cofauver** [comment]
They could very well still be working on [the exercises from the morning jQuery class](https://github.com/SF-WDI-LABS/shared_modules/blob/master/01-front-end-basics/jquery-dom-manipulation/27-28/exercises.md) and the [short jQuery lab](https://github.com/sf-wdi-27-28/jquery-dom-lab) that we hope for them to submit.

**Comment by tgaff** [comment]
@cofauver you want them to completely finish those, right?  What about submission?  I don't want to give them too much to submit.

**Comment by nathanallen** [comment]
I vote for the jQuery lab https://github.com/sf-wdi-27-28/jquery-dom-lab. I will extend it with some additional challenges. (@jlopker I reverted having them switch to the solution branch -- I think it would cause problems.)

@cofauver @jlopker -- I recommend abandoning the "Indiana Jones" exercise unless you think you can salvage it. I've moved hack-github into a separate repo (https://github.com/sf-wdi-27-28/hack-github-with-jquery) I think it would be a great in-class intro lab.

**Comment by bgveenstra** [comment]
I'd like them to finish the `click` and `keypress` challenges from the [events lab](https://github.com/sf-wdi-27-28/events_lab).  I was going to say I could extend it with some CSS and more control-flow oriented stuff lol

**Comment by nathanallen** [comment]
Ooo. I change my mind, @bgveenstra is right. Events lab is the clear winner here. But if students find it too hard they could have the option to do https://github.com/sf-wdi-27-28/jquery-dom-lab instead.

FWIW, Events Lab is pretty challenging. I usually give students 20-30 minutes per exercise so that they START ALL of them in class, and FINISH NONE!

**Comment by nathanallen** [comment]
```
1. Due Tonight: [Events Lab](https://github.com/sf-wdi-27-28/events_lab) - do as many as you can, but at a minimum finish `click` and `keypress`.
2. If you feel shaky on jQuery Events and you want more practice with DOM Manipulation, try this [jQuery Manipulation Lab](https://github.com/sf-wdi-27-28/jquery-dom-lab)
```

**Comment by tgaff** [comment]
No one's interested in a jQuery variant of the (admittedly long and challenging) LoTR lab?  https://github.com/sf-wdi-26/modules/blob/master/w01/d04/m3-LoTR-lab/solution-code/app/scripts/fellowship.js

**Comment by nathanallen** [comment]
Oh man is that an epic lab! I think we have enough material. Might be a good one for a weekend review.
