### ISSUE TITLE
express w/ or without controllers

### ISSUE THREAD

**Issue by tgaff** [SF-WDI-LABS/shared_modules#71]
We previously looked at 26's code and thought it was better organized.  They have controllers for each route and use `express.Router`.  We also considered that this might be overly complicated especially on the first day.

Please discuss, should we:
1. Stick with our [traditional approach](https://github.com/SF-WDI-LABS/shared_modules/tree/master/02-express-mongo-crud/express-params-queries/25#middleware) of all the routes in `server.js`.  See also this [lab solution](https://github.com/sf-wdi-25/toEatly/blob/solution/server.js) 
2. Move immediately to putting each route in controllers and using `express.Router`
   see an example of that [here](https://github.com/sf-wdi-26/modules/tree/master/w07/d01/m4-express-routes-lab/solution-code).  :warning: Note that this requires re-writing pretty much all of our Node stuff.
3. Delay this and start with the traditional approach, later (maybe the next day with Todo Lab, or the next week with Tunely) switch to Router and controllers. 
4. Something even better that you'll explain to us here.  :grey_question: 
5.  Juliana suggested what I'm calling a namespace-less mountable app (no router) She also suggested calling the files `resources` instead of `controllers`:

``` js
module.exports = function(app) {
​
  app.get('/api/admin/unconfirmed-users', auth.ensureAuthenticated, auth.ensureAdmin, function (req, res) {
    User.find({ confirmedAt: null }, '+email').exec(function (err, users) {
      res.send(users)
    })
  })
}
```

Please note that this issue is time-sensitive.  Next week's lessons are already due and last-minute changes are bad news bears.  :bear:

**Comment by tgaff** [comment]
I _think_ we said we'd go with 3, but I'm not sure we got consensus there.

**Comment by jlopker** [comment]
i think i'm leaning towards 2. it's not a huge amount of more files and i would rather not have to deal with the confusion later. i also think that this pattern would help with understanding MVC. but i'm willing to be convinced of something else.

**Comment by tgaff** [comment]
Nathan said: 

> " One option might be to separate out controllers starting with MEAN stack.  And use inline functions from day one so they get familiar with naming conventions: eg todoShow, todoIndex, etc.
> We should consider stubbing empty controllers, a la rails, especially because of export/import.  Plus it would enforce REST pattern.  "

**Comment by tgaff** [comment]
A loose lunchtime poll showed that: 
Justin: is somewhat on the fence but leaning toward 3 (delay and ask Nathan to do it the next day)
Cory:  Willing to let us choose.
Brianna: Very much in favor of the Router and controllers.
Juliana: Doesn't like router but likes the idea of controllers in separate files.  (Note: maybe I misunderstood since this conflicts a little with @jlopker above)

**Comment by tgaff** [comment]
I've added an example to Tuesday's TodoApp. https://github.com/SF-WDI-LABS/test-driven-todo-api/blob/use_separate_controllers_no_router/server.js
This:
- does not use Router
- does use module-pattern and external controllers
- was slapped together really fast...could be improved

@jlopker is this what you meant?

**Comment by tgaff** [comment]
5:  Juliana suggested what I'm calling a namespace-less mountable app (no router) She also suggested calling the files `resources` instead of `controllers`:

``` js
module.exports = function(app) {
​
  app.get('/api/admin/unconfirmed-users', auth.ensureAuthenticated, auth.ensureAdmin, function (req, res) {
    User.find({ confirmedAt: null }, '+email').exec(function (err, users) {
      res.send(users)
    })
  })
}
```

**Comment by bgveenstra** [comment]
What does 5 look like on the other side, when we `require`?
```
var adminModuleFunction = require('path/to/adminFile.js');
adminModuleFunction(app);
```
??

**Comment by bgveenstra** [comment]
I can get behind the all routes in server.js, controllers as separate module structure travis showed off  in https://github.com/SF-WDI-LABS/test-driven-todo-api/blob/use_separate_controllers_no_router/server.js, but suggest naming the functions within the controllers either just the verb part or verbResource:

current:
```js
// get all todos
app.get('/api/todos', controllers.todos.todoIndex);
// create new todo
app.post('/api/todos', controllers.todos.todoCreate);
```

suggest:
```js
app.get('/api/todos', controllers.todos.index); 
app.get('/api/todos', controllers.todos.create);
// or
app.get('/api/todos', controllers.todos.indexTodos);
app.get('/api/todos', controllers.todos.createTodo);
```

**Comment by tgaff** [comment]
OK.  Nathan is out on Monday and unavailable for comment.  If we changed Monday's lesson, that would force @cofauver to change Tuesday's and then Nathan would arrive Tuesday morning to find that we'd pulled the rug out from under him.  I would hate to have that happen to me and don't want to do it to him.  Plus I think Cory is still getting up to speed a little bit and asking him to change it all at last minute on the weekend seems a little sad.

**Comment by tgaff** [comment]
We can still discuss introducing controllers and maybe Router later-on. (maybe around the time we get 2 models)

**Comment by tgaff** [comment]
:camel: :cactus: :cake: :ramen: :dromedary_camel: :dragon: :microphone: :100: :+1: :rabbit: :dancers: :camel: :cactus: :cake: :ramen: :dromedary_camel: :dragon: :microphone: :100: :+1: :rabbit: :dancers: 

So a meeting of 4 today (BV, JL, CF, TG) determined that on Thursday afternoon the module pattern would be introduced and we'd go with:
- controllers from then on (using module pattern)
- no Express Router
- server.js is effectively a router

Effectively that's the example here: https://github.com/SF-WDI-LABS/test-driven-todo-api/blob/use_separate_controllers_no_router/server.js  but with a few minor changes like `require` each controller separately and name functions 'index', 'show', 'create' etc.

That puts this right after learning mongoose and therefore reinfoces module pattern.  It also is reasonably Railsy.

**Comment by tgaff** [comment]
This is answered.  Closing.
