### ISSUE TITLE
27-28-w03-d01-HW  homework

### ISSUE THREAD

**Issue by tgaff** [SF-WDI-LABS/shared_modules#79]
**Express Docs, REST reading (CF)**

**Comment by tgaff** [comment]
@cofauver Justin and I would like them to read about middleware tonight: https://github.com/SF-WDI-LABS/shared_modules/blob/master/02-express-mongo-crud/express-params-queries/27-28/middleware_reading.md

**Comment by bgveenstra** [comment]
Readings on this one are probably more than necessary, but I like the RESTful route pseudocoding exercise from 22/23: https://github.com/sf-wdi-22-23/modules-22/blob/master/w03-intro-backend-with-express/d1-homework.md

**Comment by tgaff** [comment]
^ needs some typo cleanup but otherwise great.  I was hoping we could assign them to write a few routes.
