### ISSUE TITLE
27-28-w03-d02-HW   homework

### ISSUE THREAD

**Issue by tgaff** [SF-WDI-LABS/shared_modules#80]
**Express build drills**

**Comment by cofauver** [comment]
Complete and submit [the lab](https://github.com/sf-wdi-27-28/test-driven-todo-api) that they spent time working on today!

**Comment by bgveenstra** [comment]
I agree with Cory, continuing the lab until they have index (show all), create, and delete.  

But, if we do have them do 25's [express setup drills](https://github.com/sf-wdi-25/express_setup_drills), either change the stretch to be client-side templating since they haven't seen server-side, or make it clear server-side is a large stretch and link to a guide somewhere.

**Comment by bgveenstra** [comment]
I modified an activity from 22/23 and/or have extra readings to suggest to prep for tomorrow. The activity is currently living on my personal github, so do move it if using it.  

1) Continue the lab from today. If you are showing all todos on the index, creating new todos, and deleting todos, you're in a good place.  Submit with a pull request, and remember comments to let us know comfort, completeness, and any other thoughts you'd like to share.

2) Explore MongoDB and Mongoose with [this introductory activity](https://github.com/bgveenstra/mongoose-getting-started). We'll go over all this in class.  Get as far as you can in about 45 minutes, then give us a pull request to show where you're at. Add comfort, completeness, and any other thoughts you'd like to share with us to your pull request comment. 

Edit: Moving reading, non-activity option to own comment.

**Comment by bgveenstra** [comment]
Here are the readings from activity, with some words/concepts to look out for. probably more realistic than having students do the whole activity, assuming they'll need significant time on the lab tonight.

2) Read only the first page of MongoDB's [Introduction](https://docs.mongodb.org/getting-started/cpp/introduction/). You should get an idea of what a MongoDB _document_ is and what a MongoDB _collection_ is.  The rest of the MongoDB docs are good and interesting, but mongoose's syntax is a little different, so let's move on.

3)  Read over [mongoose's quick start guide](http://mongoosejs.com/docs/). Also read the first few sections of Mongoose's [guide](http://mongoosejs.com/docs/guide.html), up through the section on creating a model. (If you're curious and have a few more minutes, read about creating instance methods with `someSchema.methods` and static methods with `someSchema.statics`. We don't recommend reading beyond there for now.) Figure out a brief summary of what a mongoose _schema_ is, what a mongoose _model_ is, and how they're different. Get a feel for the basic syntax mongoose uses to make a new document, save the document, and find documents later.

**Comment by tgaff** [comment]
there's no way they can do this and express drills :-/
